'use client';

import Link from 'next/link';
import { DocumentationShell, useDocumentationText } from '../dokumentasjon/documentation-shell';
import styles from '../dokumentasjon/documentation.module.css';

function AboutContent() {
  const text = useDocumentationText();
  return <main id="main" className={styles.main}>
    <div className={styles.hero}><Link href="/assistent" className={styles.back}>{text('Til samtalen', 'Back to the conversation')}</Link><h1>{text('Fortell én gang. Behold kontrollen.', 'Tell us once. Stay in control.')}</h1><p>{text('Team Oslo bygger en samtalebasert MVP for å forberede flere kommunale tjenester fra én livssituasjon.', 'Team Oslo is building a conversational MVP that prepares several municipal services from one life situation.')}</p></div>
    <div className={styles.aboutContent}>
      <section className={styles.section}><h2>{text('Fra behov til felles grunnlag', 'From needs to shared information')}</h2><p>{text('Når livet endrer seg, passer behovene sjelden i ett skjema. Søk én gang samler familie/SFO, bolig og flytting i en samtale, med kilder og spørsmål som følger saken.', 'When life changes, people’s needs rarely fit one form. Søk én gang connects family/SFO, housing and moving in one conversation, with sources and questions that stay with the case.')}</p><p>{text('Du kan svare i fritekst eller med tilpassede spørsmål, lese forklaringer og se planen som en tavle. Gjenbruk av bekreftede opplysninger skal redusere gjentakelse og gjøre det tydelig hva som mangler.', 'You can answer in free text or through tailored questions, read explanations and view the plan as a board. Reusing confirmed facts reduces repetition and makes missing information visible.')}</p></section>
      <section className={styles.section}><h2>{text('Hva som skjer i MVP-en', 'What happens in the MVP')}</h2><dl className={styles.definitions}>
        <div><dt>{text('Ekte modellkall', 'Real model calls')}</dt><dd>{text('Microsoft Agent Framework i Python bruker en AI-modell til koordinering og parallelle spesialistanalyser. Agentene foreslår; de avgjør ikke saken.', 'Microsoft Agent Framework in Python uses an AI model for coordination and parallel specialist analysis. Agents propose; they do not decide the case.')}</dd></div>
        <div><dt>{text('Kontrollerbare kilder', 'Traceable sources')}</dt><dd>{text('Samtale, dokumenter, sandkassedata og veiledningsutdrag vises med sin kilde. Et sitat er sporbarhet, ikke garanti for at modellen har forstått riktig.', 'Conversation, documents, sandbox data and guidance excerpts retain their sources. A quotation provides traceability, not a guarantee that the model understood correctly.')}</dd></div>
        <div><dt>{text('Faste kontroller', 'Deterministic checks')}</dt><dd>{text('Node validerer opplysninger. Etter særskilt samtykke henter SFO et deterministisk regelresultat fra KS-sandkassen; bolig og flytting får sjekklister.', 'Node validates facts. After separate consent, SFO receives a deterministic rule result from the KS sandbox; housing and moving receive checklists.')}</dd></div>
        <div><dt>{text('Mennesket bekrefter', 'People confirm')}</dt><dd>{text('Du bekrefter eller avviser fakta, løser konflikter og godkjenner gjeldende plan separat. Resultatet er en lokal dokumentpakke. Ingen søknad sendes.', 'You confirm or reject facts, resolve conflicts and separately approve the current plan. The result is a local case packet. No application is submitted.')}</dd></div>
      </dl></section>
      <section className={styles.section}><h2>{text('En workshop, ikke offentlige registre', 'A workshop, not public registers')}</h2><p>{text('KS sin offisielle workshop tilbyr API-er med syntetiske testpersoner og simulatorer for Fiks og Digdir. De kjøres lokalt; de er ikke reelle Folkeregister- eller Skatteetaten-oppslag.', 'The official KS workshop provides APIs with synthetic test citizens and simulators for Fiks and Digdir. They run locally; they are not real Population Register or Tax Administration lookups.')}</p><p>{text('Inntekt krever et eget samtykke i testflyten. Kildevisningen skal vise hvilke opplysninger som faktisk ble hentet. Valg av testdata erstatter ikke et rettslig grunnlag for en kommunal tjeneste.', 'Income requires separate consent in the test flow. The source view shows which information was actually retrieved. Choosing test data does not establish a legal basis for a municipal service.')}</p><p><a href="https://github.com/ks-no/workshop-ai/blob/main/docs/README.md">{text('Les arrangørens dokumentasjon', 'Read the organiser’s documentation')}</a></p></section>
      <section className={styles.section} id="personvern"><h2>{text('Personvern og minne', 'Privacy and memory')}</h2><p>{text('Bruk bare testopplysninger. Samtale, kilder, dokumenttekst og bekreftelser lagres i SQLite på appens maskin i 24 timer fra opprettelsen. De siste 20 meldingene beholdes; kilder og faktahistorikk lagres separat.', 'Use test information only. Conversation, sources, document text and confirmations are stored in SQLite on the app’s machine for 24 hours from creation. The latest 20 messages are retained; sources and fact history are stored separately.')}</p><p>{text('Hendelser forlenger ikke levetiden. Utløpte saker slettes ved neste databasebruk. Reload og serverrestart beholder en gyldig sak, men en avbrutt analyse må startes på nytt.', 'Activity does not extend the lifetime. Expired cases are removed at the next database access. Reload and server restart preserve a valid case, but an interrupted analysis must be started again.')}</p><p>{text('Utvalgt samtale- og dokumenttekst behandles av AI-modellen. Hele KS-registerøyeblikksbildet blir på serveren; hver spesialist får bare eksakte utdrag som er relevante for oppgaven. Modellkontekst er merket privat og ubetrodd, og agentene har ingen tool- eller handlingskapasitet.', 'Selected conversation and document text is processed by the AI model. The full KS register snapshot stays on the server; each specialist receives only exact excerpts relevant to its task. Model context is labelled private and untrusted, and agents have no tool or action capability.')}</p><p>{text('«Avslutt og slett» fjerner appens lokale sak og dokumenttekst. Nedlastede dokumentpakker og originalfiler må slettes separat. Sletting tilbakekaller ikke allerede utførte modellkall eller andre systemers historikk.', '“End and delete” removes the app’s local case and document text. Downloaded case packets and original files must be deleted separately. Deletion does not recall completed model calls or other systems’ history.')}</p></section>
      <section className={styles.section}><h2>{text('Det neste steget krever mennesker', 'The next step needs people')}</h2><p>{text('MVP-en har ingen BankID-innlogging, ekte registertilgang, automatisk rettighetsavgjørelse eller kommunal innsending. Fagpersoner må kontrollere regler, datagrunnlag, satser og videre behandling før en virkelig tjeneste kan tas i bruk.', 'The MVP has no BankID sign-in, real register access, automated entitlement decision or municipal submission. Professionals must review rules, data, rates and processing before a real service can be introduced.')}</p><p>{text('Team Oslo viser en mulig arbeidsmåte: la teknologien forberede og forklare, og la innbyggeren og fagpersonen beholde beslutningene.', 'Team Oslo demonstrates a possible way of working: technology prepares and explains, while the citizen and professional retain the decisions.')}</p><div className={styles.actions}><Link href="/dokumentasjon">{text('Utforsk dokumentasjonen og diagrammene', 'Explore the documentation and diagrams')}</Link><Link href="/assistent">{text('Til samtalen', 'Back to the conversation')}</Link></div></section>
    </div>
  </main>;
}

export default function AboutPage() { return <DocumentationShell active="about"><AboutContent /></DocumentationShell>; }
