'use client';

import Link from 'next/link';
import { useRef, useState } from 'react';
import { PktSelect } from '../../components/punkt-react';
import { AssistantButton } from '../../components/assistant-controls';
import { DocumentationShell, useDocumentationText } from './documentation-shell';
import styles from './documentation.module.css';

const diagrams = [
  ['architecture', 'Arkitektur', 'Architecture', 'Ansvar mellom nettleser, Node, Python og AI-modellen.', 'Responsibilities across the browser, Node, Python and the AI model.'],
  ['workflow', 'Arbeidsflyt', 'Workflow', 'Fra behov til en plan og menneskelig bekreftelse.', 'From needs to a plan and human confirmation.'],
  ['sequence', 'Sekvens', 'Sequence', 'Modellkall, private verktøykall og parallelle spesialister.', 'Model calls, private tool callbacks and parallel specialists.'],
  ['data-flow', 'Dataflyt', 'Data flow', 'Kilder, kontroller og bekreftet saksgrunnlag.', 'Sources, validation and confirmed case information.'],
  ['lifecycle', 'Livsløp', 'Lifecycle', 'Hvordan fakta endres, saken utløper og minnet slettes.', 'How facts change, the case expires and memory is deleted.'],
] as const;

function DiagramViewer() {
  const text = useDocumentationText();
  const [selected, setSelected] = useState<string>('architecture');
  const [zoom, setZoom] = useState(100);
  const viewport = useRef<HTMLDivElement>(null);
  const [id, nb, en, nbDescription, enDescription] = diagrams.find(item => item[0] === selected) ?? diagrams[0];
  return <>
    <div className={styles.diagramControls}><div><PktSelect id="documentation-diagram" label={text('Velg diagram', 'Choose a diagram')} value={selected} onChange={event => { setSelected(event.target.value); setZoom(100); }}>{diagrams.map(([value, no, english]) => <option key={value} value={value}>{text(no, english)}</option>)}</PktSelect></div>
      <AssistantButton skin="secondary" aria-label={text('Zoom ut', 'Zoom out')} disabled={zoom <= 50} onClick={() => setZoom(value => Math.max(50, value - 25))}>−</AssistantButton><AssistantButton skin="secondary" onClick={() => setZoom(100)}>{text('Tilpass', 'Fit')}</AssistantButton><AssistantButton skin="secondary" aria-label={text('Zoom inn', 'Zoom in')} disabled={zoom >= 800} onClick={() => setZoom(value => Math.min(800, value + 25))}>+</AssistantButton><AssistantButton skin="secondary" onClick={() => setZoom(Math.min(800, Math.max(100, Math.round(240000 / (viewport.current?.clientWidth || 800)))))}>{text('Lesestørrelse', 'Reading size')}</AssistantButton><output aria-live="polite">{zoom} %</output>
    </div>
    <div ref={viewport} className={styles.diagramViewport} tabIndex={0} aria-label={text('Rullbart diagram. Bruk zoom for å lese detaljene.', 'Scrollable diagram. Use zoom to read details.')}>
      {/* The same local SVG is available as a download; percentage zoom preserves its detail. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={`/diagrams/agentic-${id}.svg`} alt={text(`${nb}: ${nbDescription}`, `${en}: ${enDescription}`)} style={{ width: `${zoom}%` }} />
    </div>
    <p className={styles.caption}>{text(nbDescription, enDescription)} {text('Diagramtekstene er på norsk. Forklaringene på denne siden finnes også på engelsk.', 'Diagram labels are in Norwegian. The explanations on this page are also available in English.')}</p>
    <div className={styles.actions}><a href={`/diagrams/agentic-${id}.png`} download>{text('Last ned PNG', 'Download PNG')}</a><a href={`/diagrams/agentic-${id}.svg`} download>{text('Last ned SVG', 'Download SVG')}</a><a href={`/diagrams/agentic-${id}.mmd`} download>{text('Last ned Mermaid-kilde', 'Download Mermaid source')}</a><a href="/diagrams/index.html">{text('Åpne hele diagramsamlingen', 'Open the full diagram collection')}</a></div>
  </>;
}

function DocumentationContent() {
  const text = useDocumentationText();
  const topics = [['mvp', 'Hva MVP-en gjør', 'What the MVP does'], ['bruk', 'Prøv samtalen', 'Try the conversation'], ['agenter', 'Agenter og tjenester', 'Agents and services'], ['minne', 'Kilder og kontroll', 'Sources and control'], ['diagrammer', 'Fem diagrammer', 'Five diagrams'], ['kjoring', 'Kjør lokalt', 'Run locally'], ['grenser', 'Grenser og kilder', 'Limits and sources']];
  return <main id="main" className={styles.main}>
    <div className={styles.hero}><Link className={styles.back} href="/">{text('Til samtalen', 'Back to the conversation')}</Link><h1>{text('Slik virker Søk én gang', 'How Søk én gang works')}</h1><p>{text('En praktisk veiviser til samtalen, agentene, kildegrunnlaget og valgene du selv kontrollerer.', 'A practical guide to the conversation, agents, sources and decisions you control.')}</p></div>
    <div className={styles.layout}><nav className={styles.index} aria-label={text('På denne siden', 'On this page')}><h2>{text('På denne siden', 'On this page')}</h2><div>{topics.map(([id, nb, en]) => <a key={id} href={`#${id}`}>{text(nb, en)}</a>)}</div></nav><div className={styles.content}>
      <section id="mvp" className={styles.section}><h2>{text('Én samtale, tre tjenesteområder', 'One conversation, three service areas')}</h2><p>{text('Team Oslo utforsker hvordan innbyggeren kan beskrive en livssituasjon én gang og få et felles grunnlag for familie/SFO, bolig og flytting.', 'Team Oslo explores how a citizen can describe a life situation once and prepare shared information for family/SFO, housing and moving.')}</p>
        <dl className={styles.definitions}><div><dt>{text('Familie og SFO', 'Family and SFO')}</dt><dd>{text('Forbereder familieopplysninger og SFO-vurdering. KS sin regelmotor gir en vurdering av sandkassegrunnlaget etter samtykke.', 'Prepares family information and an SFO assessment. The KS rules engine assesses the sandbox information after consent.')}</dd></div><div><dt>{text('Bolig og bostøtte', 'Housing and housing allowance')}</dt><dd>{text('Samler inntekts- og boligdokumentasjon og neste steg. Beregner ikke bostøtte eller avgjør rett til støtte.', 'Collects income and housing documentation and next steps. It does not calculate housing allowance or determine eligibility.')}</dd></div><div><dt>{text('Flytting', 'Moving')}</dt><dd>{text('Forbereder adresse, tidspunkt, hvem som flytter og videre oppfølging. Sender ingen flyttemelding.', 'Prepares the address, date, people moving and follow-up. It does not submit a change-of-address notice.')}</dd></div></dl>
      </section>
      <section id="bruk" className={styles.section}><h2>{text('Prøv en samlet livssituasjon', 'Try a connected life situation')}</h2><blockquote className={styles.example}>{text('Jeg har mistet jobben. Jeg har barn som bruker SFO, trenger hjelp med boligutgiftene og skal flytte til en annen kommune. Hva bør jeg ordne først?', 'I have lost my job. My children use SFO, I need help with housing costs and I am moving to another municipality. What should I arrange first?')}</blockquote>
        <ol><li>{text('Skriv behovet med egne ord. Du velger ikke kategori; agenten finner én eller flere relevante tjenester.', 'Describe the need in your own words. You do not choose a category; the agent finds one or more relevant services.')}</li><li>{text('Et generelt spørsmål besvares fra offentlig veiledning uten personoppslag. En personlig SFO-vurdering viser «Handling kreves» i samtalen før KS kan brukes.', 'A general question is answered from public guidance without a personal lookup. A personal SFO assessment shows “Action required” in the conversation before KS can be used.')}</li><li>{text('Samtykk for å hente syntetiske KS-opplysninger og fortsette analysen automatisk, eller avslå for å svare manuelt. Det finnes ingen egen «Hent fra KS»-knapp i oversikten.', 'Consent to retrieve synthetic KS information and continue the analysis automatically, or decline to answer manually. There is no separate “Retrieve from KS” button in the overview.')}</li><li>{text('Åpne «Se kilde», les sitatet og bekreft eller avvis hver opplysning som KI har foreslått. Opplysninger du selv skriver i tydelig merkede felt, regnes som din bekreftelse.', 'Open “View source”, read the quotation and confirm or reject each fact proposed by AI. Information you enter in clearly labelled fields counts as your confirmation.')}</li><li>{text('Når alle forslag er avklart, oppdaterer agentene planen automatisk. «Oppdater planen» brukes bare til å prøve en mislykket analyse på nytt.', 'When all proposals are resolved, the agents update the plan automatically. “Update plan” is only used to retry a failed analysis.')}</li><li>{text('Et tydelig «Neste steg» vises i samtalen når noe må kontrolleres eller planen er klar. Velg «Oversikt» eller «Tavle» og se over det som gjenstår før du lager en lokal dokumentpakke.', 'A clear “Next step” appears in the conversation when something needs review or the plan is ready. Choose “Overview” or “Board” and review what remains before creating a local case packet.')}</li></ol>
        <p>{text('For SFO vises selve KS-resultatet, inntektsgrunnlaget, terskelen og opplysningene du ga i et eget svarfelt. Hvis grunnlagene ikke stemmer overens, sier feltet tydelig at spørsmålet ikke er endelig avklart.', 'For SFO, a dedicated answer panel shows the KS result, its income basis and threshold, and the information you provided. If the bases do not match, the panel clearly says that the question is not finally resolved.')}</p><p>{text('En lokal dokumentpakke lagrer resultatet og det som må følges opp. At pakken er lagret betyr ikke at kommunen har avgjort spørsmålet.', 'A local preparation packet records the result and the follow-up needed. Saving the packet does not mean that the municipality has decided the question.')}</p><p>{text('Skjemaet tilbyr ja/nei, tall, dato og fritekst etter spørsmålet. Verdier som innbyggeren skriver i tydelig merkede felt lagres direkte som innbyggerens egen bekreftelse. Bare opplysninger som KI trekker ut fra fritekst eller dokumenter må bekreftes separat.', 'The form offers yes/no, numbers, dates and free text as appropriate. Values entered in clearly labelled fields are stored directly as the citizen’s own confirmation. Only facts extracted by AI from free text or documents require separate confirmation.')}</p><p>{text('NO/EN-valget endrer grensesnittet. KI-svar følger spørsmålets språk eller et uttrykkelig språkønske. Kildesitater beholder originalspråket.', 'The NO/EN selector changes the interface. AI replies follow the question’s language or an explicit language request. Source quotations keep their original language.')}</p><p>{text('Svar kan vise Markdown med lister, tabeller og lenker. Rå HTML, bilder og kjørbare lenker vises ikke.', 'Replies can display Markdown lists, tables and links. Raw HTML, images and executable links are not displayed.')}</p>
      </section>
      <section id="agenter" className={styles.section}><h2>{text('En reell agentflyt', 'A real agent workflow')}</h2><p>{text('Microsoft Agent Framework kjører en Python-prosess for hver analyse. En AI-modell velger relevante tjenester, og spesialistagenter analyserer de valgte områdene parallelt.', 'Microsoft Agent Framework runs a Python process for each analysis. An AI model selects relevant services, and specialist agents analyse the selected areas in parallel.')}</p>
        <p>{text('Samtalen viser gjeldende agentoppgave i et kompakt aktivitetsfelt. Feltet kan åpnes for å se alle agentoppgavene; en valgt oppgave viser status, varighet og den tilhørende hendelseslinjen i fanen Aktivitet.', 'The conversation shows the current agent task in a compact activity control. Open it to see all agent tasks; selecting one shows its status, duration and related event timeline in the Activity tab.')}</p>
        <dl className={styles.definitions}><div><dt>{text('Python og frameworket', 'Python and the framework')}</dt><dd>{text('Eier agentutførelse, fordeling til tre tjenestegrener og samling av resultater. Uvalgte grener avsluttes uten modellkall.', 'Own agent execution, dispatch to three service branches and result collection. Unselected branches finish without a model call.')}</dd></div><div><dt>Node</dt><dd>{text('Kontrollerer kilder og modellforslag, kjører avgrensede domeneverktøy, lagrer saken og håndhever menneskelige valg.', 'Validates sources and model proposals, runs bounded domain tools, stores the case and enforces human decisions.')}</dd></div><div><dt>{text('AI-modell', 'AI model')}</dt><dd>{text('Mottar bare utvalgte utdrag for koordinering og spesialistanalyse. Saksminnet blir på appens maskin.', 'Receives only selected excerpts for coordination and specialist analysis. Case memory stays on the app’s machine.')}</dd></div></dl>
        <details><summary>{text('Teknisk kontrakt og feil', 'Technical contract and failures')}</summary><div><p>{text('Python og Node bruker private JSONL-rør, uten en ekstra HTTP-server. Python validerer modellens JSON mot skjemaet, og Node validerer på nytt med Zod og kildekontroll.', 'Python and Node use private JSONL pipes without an additional HTTP server. Python validates model JSON against its schema; Node validates again with Zod and source checks.')}</p><p>{text('Modellkontekst merkes privat og ubetrodd med FIDES-etiketter. Agentene har bare analysekapasitet; en fail-closed middleware stopper kjøringen dersom et tool eller en handling legges til.', 'Model context is labelled private and untrusted with FIDES labels. Agents have analysis capability only; fail-closed middleware stops the run if a tool or action is added.')}</p><p>{text('Én formatretting er tillatt innen samme tidsbudsjett, normalt 90 sekunder per agent. Nettverksfeil gir ikke automatisk omforsøk. En feil vises og blokkerer endelig klargjøring.', 'One format repair is allowed within the same time budget, normally 90 seconds per agent. Network failures do not trigger automatic retries. A failure is visible and blocks final preparation.')}</p></div></details>
      </section>
      <section id="minne" className={styles.section}><h2>{text('Kilder følger opplysningene', 'Sources stay with the facts')}</h2><p>{text('Samtaletekst, dokumentuttrekk, sandkassedata og lagret veiledning har ulike kildeidentiteter. Forslag må vise et eksakt sitat med linjer, og side for PDF.', 'Conversation text, document extracts, sandbox data and saved guidance have distinct source identities. Proposals must show an exact quotation with lines, and a page for PDFs.')}</p><p>{text('Fanen Kilder samler alle kilder og original-lenker i én visning. Under hvert KI-svar vises kildene som faktisk ble brukt, slik at grunnlaget kan kontrolleres uten å lete gjennom hele saken.', 'The Sources tab collects all sources and original links in one view. Each AI answer lists the sources actually used, so its basis can be checked without searching through the whole case.')}</p><p>{text('Et sitat viser hvor teksten kommer fra. Det beviser ikke at en tolkning er riktig. KI-tolkning må kontrolleres, og en ny verdi erstatter ikke en bekreftet verdi uten ditt valg.', 'A quotation shows where the text came from. It does not prove an interpretation is correct. AI interpretation needs review, and a new value cannot replace a confirmed one without your choice.')}</p>
        <div className={styles.callout}><h3>{text('Kontroller og fullfør', 'Review and complete')}</h3><p>{text('Forslag og konflikter må avklares. I Neste steg ser innbyggeren hva som fortsatt må følges opp, fullfører gjennomgangen og får tydelige valg videre. Det opprettes en lokal oppsummering og JSON-kvittering; ingen søknad sendes.', 'Proposals and conflicts must be resolved. Next steps shows what still needs follow-up, lets the citizen complete the review, and presents clear actions afterwards. It creates a local summary and JSON receipt; no application is submitted.')}</p></div>
        <p>{text('SQLite lagrer saken i 24 timer fra opprettelsen, med de siste 20 meldingene og eget kilde- og faktaminne. Aktivitet forlenger ikke fristen. Utløpte saker ryddes ved neste databasebruk.', 'SQLite stores the case for 24 hours from creation, with the latest 20 messages and separate source and fact memory. Activity does not extend this period. Expired cases are removed at the next database access.')}</p><p>{text('Reload og serverrestart beholder en gyldig sak. En avbrutt analyse må kjøres på nytt; frameworket har ingen egen varig checkpoint av samtalen.', 'Reload and server restart preserve a valid case. An interrupted analysis must be rerun; the framework keeps no separate durable conversation checkpoint.')}</p>
        <details><summary>{text('Dokumenter, KS-data og sletting', 'Documents, KS data and deletion')}</summary><div><p>{text('TXT og PDF med tekst støttes: 1,5 MB per fil, opptil 10 PDF-sider, 14 000 teksttegn og fire dokumenter per sak. Skannede bilder leses ikke. Dokumenter er ubetrodd informasjon, aldri instruksjoner til agenten.', 'TXT and text-based PDF are supported: 1.5 MB per file, up to 10 PDF pages, 14,000 text characters and four documents per case. Scanned images are not read. Documents are untrusted information, never instructions to the agent.')}</p><p>{text('Hele KS-registerøyeblikksbildet blir på serveren. En spesialist får bare eksakte utdrag som allerede er knyttet til relevante fakta; et registerresultat uten et slikt utdrag sendes ikke til modellen.', 'The full KS register snapshot stays on the server. A specialist receives only exact excerpts already tied to relevant facts; a register result without such an excerpt is not sent to the model.')}</p><p>{text('«Avslutt og slett» fjerner lokalt saksminne og dokumenttekst. Nedlastede filer og allerede utførte modellkall slettes ikke av denne handlingen.', '“End and delete” removes local case memory and document text. Downloaded files and already completed model calls are not deleted by this action.')}</p></div></details>
      </section>
      <section id="diagrammer" className={styles.section}><h2>{text('Fem perspektiver på løsningen', 'Five views of the service')}</h2><p>{text('Diagrammene kan lastes ned som PNG eller SVG, med redigerbar Mermaid-kilde. Hele samlingen kan brukes offline.', 'The diagrams can be downloaded as PNG or SVG, with editable Mermaid sources. The full collection works offline.')}</p><DiagramViewer /></section>
      <section id="kjoring" className={styles.section}><h2>{text('Kjør appen lokalt', 'Run the app locally')}</h2><p>{text('For utviklere: bruk Node.js 22.18 eller nyere og Python 3.11 eller nyere. Kopier .env.example til .env.local og fyll inn dine egne serverinnstillinger.', 'For developers: use Node.js 22.18 or later and Python 3.11 or later. Copy .env.example to .env.local and enter your own server settings.')}</p><pre className={styles.code}><code>{'npm ci\nnpm run setup:backend\nnpm run dev'}</code></pre><p>{text('Åpne http://127.0.0.1:3210. Python-prosessen startes og avsluttes av appen for hver analyse. Stopp din app med Ctrl+C før en ny oppstart.', 'Open http://127.0.0.1:3210. The app starts and closes a Python process for each analysis. Stop your app with Ctrl+C before starting another instance.')}</p>
        <details><summary>{text('Modellinnstillinger og verifikasjon', 'Model settings and verification')}</summary><div><p>{text('Tilgangen til AI-modellen konfigureres på serveren i .env.local. Hemmeligheter blir på serveren. Leverandør og modell per rolle kan byttes i drift via administrasjonsendepunktet, uten omstart; nye hemmeligheter i .env.local krever fortsatt omstart.', 'Access to the AI model is configured on the server in .env.local. Secrets stay on the server. Provider and model per role can be switched at runtime through the admin endpoint, without a restart; new secrets in .env.local still require a restart.')}</p><pre className={styles.code}><code>{'ASSISTANT_MODEL_TIMEOUT_MS=90000\nASSISTANT_DATA_DIR=.data\n\nnpm run typecheck\nnpm test\nnpm run test:backend\nnpm run test:ai'}</code></pre><p>{text('test:ai bruker ekte AI-modellkall med testdata og kan koste penger. Det er ikke en simulert modelltest.', 'test:ai makes real AI model calls with test data and may incur charges. It is not a simulated model test.')}</p></div></details>
        <details><summary>{text('KS sin workshop-sandkasse', 'The KS workshop sandbox')}</summary><div><p>{text('Arrangørens workshop tilbyr lokale API-er med syntetiske data. Det er ikke et publisert registerendepunkt. Sandkassen må kjøre før appen kan hente opplysninger derfra.', 'The organiser’s workshop provides local APIs with synthetic data. It is not a published register endpoint. The sandbox must be running before the app can retrieve its information.')}</p><p>{text('Tjenestene bruker normalt port 8080 for sandbox-backend, 8081 for Fiks-simulator og 8086 for Digdir-simulator. person-022 er SFO-testpersonen. Agenten ber bare om KS-tilgang når en personlig SFO-vurdering trenger data. Ett uttrykkelig samtykke henter husstand, SFO, inntekt og regelresultat og fortsetter analysen automatisk. Ved avslag hentes ingenting, og spørsmålene kan besvares manuelt. Hentede verdier kan fortsatt rettes.', 'Services normally use port 8080 for the sandbox backend, 8081 for the Fiks simulator and 8086 for the Digdir simulator. person-022 is the SFO test citizen. The agent only requests KS access when a personal SFO assessment needs data. One explicit consent retrieves household, SFO, income and the rule result and continues the analysis automatically. If declined, nothing is retrieved and the questions can be answered manually. Retrieved values can still be corrected.')}</p><p>{text('En senere Skatteetaten-adapter må bruke de konkrete API-tilgangene Team Oslo får, Maskinporten og nødvendige rettighetspakker. Testmiljøet bruker syntetiske data; appen kan ikke hente alle skatteopplysninger gjennom ett generelt endepunkt. KS-sandkassen er derfor dagens adapter for demoen.', 'A future Norwegian Tax Administration adapter must use the specific API access granted to Team Oslo, Maskinporten and the required access packages. The test environment uses synthetic data; the app cannot retrieve all tax information through one general endpoint. The KS sandbox is therefore the demo’s current adapter.')}</p>
          <h3>{text('Alle åtte OpenAPI-kontraktene', 'All eight OpenAPI contracts')}</h3><dl className={styles.definitions}>
            <div><dt>digdir-mock</dt><dd>{text('Kjerne: ID-porten for testidentitet og Maskinporten for maskintoken. Neste UI-steg er en synlig testinnlogging i stedet for en fast testperson.', 'Core: ID-porten for test identity and Maskinporten for machine tokens. The next UI step is a visible test sign-in instead of a fixed test citizen.')}</dd></div>
            <div><dt>sandbox-backend</dt><dd>{text('Kjerne: husstand, SFO, inntektsgrunnlag, satser og deterministisk regelsjekk. Søknadsrutene brukes ikke fordi demoen ikke sender inn noe.', 'Core: household, SFO, income basis, rates and deterministic rule checks. Submission routes are unused because the demo submits nothing.')}</dd></div>
            <div><dt>fiks-simulator</dt><dd>{text('Kjerne for inntektssamtykke. Oppgaver, meldinger og SvarUt er aktuelle først når en senere demo faktisk oppretter og følger opp en sak.', 'Core for income consent. Tasks, messages and SvarUt become relevant only when a later demo actually creates and follows up a case.')}</dd></div>
            <div><dt>ai-gateway</dt><dd>{text('Ikke brukt: løsningen har allerede en avgrenset kobling til AI-modellen. En ekstra KI-gateway ville duplisert ansvar og spor.', 'Unused: the solution already has a bounded connection to the AI model. Another AI gateway would duplicate responsibilities and traces.')}</dd></div>
            <div><dt>process-agent</dt><dd>{text('Ikke brukt: den overlapper koordinatoren og spesialistagentene som allerede kjører i Python.', 'Unused: it overlaps the coordinator and specialist agents already running in Python.')}</dd></div>
            <div><dt>tools-api</dt><dd>{text('Ikke brukt direkte: den er en intern, åpen orkestreringsflate over de andre tjenestene. Appen kaller avgrensede, validerte adaptere på serveren.', 'Not called directly: it is an internal open orchestration surface over the other services. The app calls bounded, validated server adapters.')}</dd></div>
            <div><dt>matrikkel-mock</dt><dd>{text('Mulig utvidelse for bolig, flytting og eierskap. Den trengs ikke for å svare på SFO-spørsmålet.', 'Possible extension for housing, moving and ownership. It is not needed to answer the SFO question.')}</dd></div>
            <div><dt>pasientjournal-mock</dt><dd>{text('Utenfor dagens omfang. Helseopplysninger tas ikke inn uten et konkret tjenestebehov, egen hjemmel og tydelig menneskelig kontroll.', 'Outside the current scope. Health data is not included without a concrete service need, separate legal authority and clear human control.')}</dd></div>
          </dl><pre className={styles.code}><code>{'npm run setup:ks\nnpm run start:ks'}</code></pre><p>{text('Kjør KS i en egen terminal og stopp med Ctrl+C etter bruk. Oppstarten bruker en festet versjon av det offisielle repoet og krever ledige porter. Appens modellkall går gjennom den serverkonfigurerte AI-modellen.', 'Run KS in a separate terminal and stop it with Ctrl+C after use. Setup uses a pinned version of the official repository and requires free ports. The app’s model calls use the server-configured AI model.')}</p><p><a href="https://github.com/ks-no/workshop-ai/tree/main/openapi">{text('Se alle OpenAPI-kontraktene', 'See all OpenAPI contracts')}</a></p><p><a href="https://github.com/ks-no/workshop-ai/blob/main/docs/deltakerstart.md">{text('Se arrangørens oppstart og testpersoner', 'See the organiser’s setup and test citizens')}</a></p><p><a href="https://skatteetaten.github.io/api-dokumentasjon/">{text('Se Skatteetatens krav til API-tilgang', 'See the Norwegian Tax Administration API access requirements')}</a></p></div></details>
      </section>
      <section id="grenser" className={styles.section}><h2>{text('Hva dette ikke avgjør', 'What this does not decide')}</h2><p>{text('Dette er en MVP med testopplysninger. Den har ingen BankID-innlogging, tilgang til virkelige registre, automatisk vedtak eller kommunal innsending. Bolig og flytting er forberedelse til menneskelig oppfølging.', 'This is an MVP using test information. It has no BankID sign-in, access to real registers, automatic decisions or municipal submission. Housing and moving prepare information for human follow-up.')}</p><p>{text('SFO-vurderingen bruker KS-sandkassens satser og kildeøyeblikksbilde. Sitatkontroll og kontroll av enkelte tall og handlingspåstander er ikke full semantisk verifikasjon.', 'The SFO assessment uses the KS sandbox rates and source snapshot. Checking quotations and some numeric or action claims is not complete semantic verification.')}</p><p>{text('Utvalgt tekst behandles av AI-modellen. Bare relevant kontekst sendes til hver agentoppgave, mens saksminnet lagres lokalt.', 'Selected text is processed by the AI model. Only relevant context is sent to each agent task, while case memory stays local.')}</p>
        <ul className={styles.sourceLinks}><li><a href="https://github.com/ks-no/workshop-ai">{text('KS: offisiell workshop og API-dokumentasjon', 'KS: official workshop and API documentation')}</a></li><li><a href="https://learn.microsoft.com/en-us/agent-framework/">Microsoft Agent Framework</a></li><li><a href="https://punkt.oslo.kommune.no/">{text('Oslo kommune: Punkt designsystem', 'City of Oslo: Punkt design system')}</a></li></ul><p><Link href="/om-demoen#personvern">{text('Les mer om Team Oslo og personvern', 'Read more about Team Oslo and privacy')}</Link></p>
      </section>
    </div></div>
  </main>;
}

export default function DocumentationPage() { return <DocumentationShell active="docs"><DocumentationContent /></DocumentationShell>; }
